#Requires -Version 5.1
<#
.SYNOPSIS
  Fetches the guild-scoped Guild Performer roster from RaidRoster and writes GuildPerformer_Data.lua.

.DESCRIPTION
  WoW addons cannot HTTP GET. Run this on a schedule (Task Scheduler every 30 min), then /reload in-game.
  Config: copy config.example.json → config.json (gitignored).

.EXAMPLE
  .\Sync-GuildPerformer.ps1
  .\Sync-GuildPerformer.ps1 -ConfigPath .\config.json -Force
#>
[CmdletBinding()]
param(
  [string]$ConfigPath = (Join-Path $PSScriptRoot "config.json"),
  [switch]$Force
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $ConfigPath)) {
  Write-Error "Missing config: $ConfigPath — copy config.example.json to config.json and set url + addonPath."
}

$config = Get-Content -Raw -Path $ConfigPath | ConvertFrom-Json
if (-not $config.url) { Write-Error "config.url is required" }
if (-not $config.addonPath) { Write-Error "config.addonPath is required" }

$addonPath = $config.addonPath.TrimEnd('\', '/')
if (-not (Test-Path $addonPath)) {
  Write-Error "addonPath not found: $addonPath"
}

$outFile = Join-Path $addonPath "GuildPerformer_Data.lua"
$etagFile = Join-Path $PSScriptRoot ".last-etag"
$format = if ($config.format) { $config.format } else { "lua" }
$url = $config.url
if ($url -notmatch '[?&]format=') {
  $sep = if ($url -match '\?') { '&' } else { '?' }
  $url = "$url${sep}format=$format"
}

$headers = @{
  "User-Agent" = "GuildPerformer-Syncer/1.0"
  "Accept"     = "text/plain"
}
if (-not $Force -and (Test-Path $etagFile)) {
  $prev = (Get-Content -Raw $etagFile).Trim()
  if ($prev) { $headers["If-None-Match"] = $prev }
}

Write-Host "GET $url"
try {
  $response = Invoke-WebRequest -Uri $url -Headers $headers -UseBasicParsing -TimeoutSec 60
} catch {
  if ($_.Exception.Response -and [int]$_.Exception.Response.StatusCode -eq 304) {
    Write-Host "304 Not Modified — roster unchanged."
    exit 0
  }
  throw
}

if ([int]$response.StatusCode -eq 304) {
  Write-Host "304 Not Modified — roster unchanged."
  exit 0
}

if ([int]$response.StatusCode -ne 200) {
  Write-Error "HTTP $($response.StatusCode)"
}

$body = $response.Content
if ([string]::IsNullOrWhiteSpace($body)) {
  Write-Error "Empty response body."
}

# Ensure the data file sets the global the addon expects.
if ($body -notmatch 'GuildPerformerDB_Import') {
  Write-Error "Response does not look like a Guild Performer lua dump."
}

$header = @"
-- Auto-generated by Guild Performer syncer $(Get-Date -Format o)
-- Source: guild export API (do not commit real roster data)
"@

Set-Content -Path $outFile -Value ($header + "`n" + $body) -Encoding UTF8
Write-Host "Wrote $outFile ($($body.Length) bytes)"

$etag = $response.Headers["ETag"]
if (-not $etag) { $etag = $response.Headers["X-Content-Hash"] }
if ($etag) {
  Set-Content -Path $etagFile -Value $etag -Encoding ASCII
}

$guildId = $response.Headers["X-Guild-Id"]
$count = $response.Headers["X-Player-Count"]
if ($guildId) { Write-Host "Guild id: $guildId  players: $count" }
Write-Host "Done. In WoW: /reload  (or /gp sync)"
exit 0
